### ISSUE TITLE
insufficient fund

### ISSUE THREAD

**Issue by cullsin** [fmsouza/ethereum-wallet#14]
Hi,

Thank you so much for the app. I am unable to do the transaction. Because I don't have currency/coin in my wallet. How do I load currency/coin in the wallet in order to make a transaction? I am getting the below error. 

![image](https://user-images.githubusercontent.com/5137598/59621078-135e4d00-914c-11e9-8c3c-69a99411fd7b.png)

**Comment by fmsouza** [comment]
Hello @cullsin,
If you want to have Ether in your wallet for the matter of testing this app, you can use the Rinkeby Faucet which sends ETH to your wallet address in the testnet, then you can make your transactions as you wish. The testnet is used only for testing purposes, so the ETH or other tokens sent in transactions has no values. The app is configured to run on the testnet as default. To use with the mainnet, you need to run the production build.

If you want to have actual ETH to make transactions in the mainnet, you need to buy ETH. This can be done via P2P or online exchanges.

**Comment by cullsin** [comment]
Hi, 

Thanks. Can you please suggest me steps to add currency into the wallet using Rinkehy Faucet. 

Raja K

**Comment by fmsouza** [comment]
@cullsin there are instructions for that in the link I posted in the previous comment.
