### ISSUE TITLE
how to resolve '@common' paths

### ISSUE THREAD

**Issue by TimDost** [fmsouza/ethereum-wallet#3]
Upon cloning the app I have issues with resolving the modules; how can I make the app recognize these @common // @components paths? Thanks in advance.

**Comment by fmsouza** [comment]
@TimDost make sure you have the latest repository updates, try to fully remove your `node_modules` and reinstall it. If all your dependencies are installed correctly, it shouldn't produce this error, as these aliases are configured in the `.babelrc` and are used to configure these paths in the build step.

Reference: https://github.com/fmsouza/ethereum-wallet/blob/master/.babelrc

**Comment by TimDost** [comment]
@fmsouza thanks! After upgrading nvm version, reinstalling node_modules and clearing cache it is working.
