### ISSUE TITLE
Crash in release mode

### ISSUE THREAD

**Issue by billtlee** [fmsouza/ethereum-wallet#9]
Hi,

I was just trying to build and run this in release mode under iOS and the app appears to crash right away with the following.  Any idea what might be causing this?

2019-05-15 23:52:38.536 [error][tid:com.facebook.react.JavaScript] TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in t
    in t
    in RCTView
    in n
    in t
    in n
    in u
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n
2019-05-15 23:52:38.537976+0800 EthereumWallet[18770:268521] TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in t
    in t
    in RCTView
    in n
    in t
    in n
    in u
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n
2019-05-15 23:52:38.542 [error][tid:com.facebook.react.JavaScript] TypeError: TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in t
    in t
    in RCTView
    in n
    in t
    in n
    in u
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n

This error is located at:
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n
2019-05-15 23:52:38.541834+0800 EthereumWallet[18770:268521] TypeError: TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in t
    in t
    in RCTView
    in n
    in t
    in n
    in u
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n

This error is located at:
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n
2019-05-15 23:52:38.543 [error][tid:com.facebook.react.JavaScript] TypeError: TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in t
    in t
    in RCTView
    in n
    in t
    in n
    in u
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n

This error is located at:
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n
2019-05-15 23:52:38.547543+0800 EthereumWallet[18770:268521] TypeError: TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in t
    in t
    in RCTView
    in n
    in t
    in n
    in u
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n

This error is located at:
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n
2019-05-15 23:52:38.549 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: TypeError: TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in t
    in t
    in RCTView
    in n
    in t
    in n
    in u
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n

This error is located at:
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n
2019-05-15 23:52:38.549537+0800 EthereumWallet[18770:268509] Unhandled JS Exception: TypeError: TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in t
    in t
    in RCTView
    in n
    in t
    in n
    in u
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n

This error is located at:
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n
2019-05-15 23:52:38.560854+0800 EthereumWallet[18770:268509] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: TypeError: TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in t
    in t
    in RCTView
    in n
    in t
    in n
    in u
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n

This error is located at:
    in e
    in RCTView
    in t
    in t
    in RCTView
    in RCTView
    in n', reason: 'Unhandled JS Exception: TypeError: TypeError: undefined is not an object (e..., stack:
r@486:732
nr@238:43523
Ur@238:56432
Ar@238:56864
si@238:61708
li@238:61128
ii@238:60256
Mr@238:59236
pi@238:66432
render@238:69043
exports@419:431
run@415:611
runApplication@415:2013
value@99:3222
<unknown>@99:805
value@99:2491
value@99:777
value@<null>:<null>
'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000103f741bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000101d9f735 objc_exception_throw + 48
	2   EthereumWallet                      0x000000010103f634 RCTFormatError + 0
	3   EthereumWallet                      0x000000010103c397 -[RCTExceptionsManager reportFatalException:stack:exceptionId:] + 507
	4   CoreFoundation                      0x0000000103f7b03c __invoking___ + 140
	5   CoreFoundation                      0x0000000103f784d5 -[NSInvocation invoke] + 325
	6   CoreFoundation                      0x0000000103f78926 -[NSInvocation invokeWithTarget:] + 54
	7   EthereumWallet                      0x000000010105278f -[RCTModuleMethod invokeWithBridge:module:arguments:] + 602
	8   EthereumWallet                      0x000000010109714b _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 255
	9   EthereumWallet                      0x0000000101096eca ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 78
	10  libdispatch.dylib                   0x00000001078a7595 _dispatch_call_block_and_release + 12
	11  libdispatch.dylib                   0x00000001078a8602 _dispatch_client_callout + 8
	12  libdispatch.dylib                   0x00000001078afb0b _dispatch_lane_serial_drain + 791
	13  libdispatch.dylib                   0x00000001078b0784 _dispatch_lane_invoke + 428
	14  libdispatch.dylib                   0x00000001078ba89a _dispatch_workloop_worker_thread + 733
	15  libsystem_pthread.dylib             0x0000000107c8f611 _pthread_wqthread + 421
	16  libsystem_pthread.dylib             0x0000000107c8f3fd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by fmsouza** [comment]
Hello @billtlee, maybe it could be related to the fact this app has been outdated for a while. My last commit was last year's August and most of the libs included in this app received updates. Possibly this error is due to some conflict between versions you have installed in your environment and the outdated ones installed in this app.

I've been very busy since then, that's why I never commited anything again. But right now I got some spare time, so I can take a look and update the app to fix these build issues. I'll update this issue once I got news.

**Comment by billtlee** [comment]
I actually was able to fix it.  I did a brand new react-native init, then brought in your code and installed all the packages with their latest release manually and rebuild it and I was able to get it to work.  Thanks!

**Comment by fmsouza** [comment]
@billtlee Awesome! :)
Would you mind create a PR with the fixes in this repo?

**Comment by billtlee** [comment]
Sorry, what's a PR?

**Comment by fmsouza** [comment]
A _Pull Request_. You can create it to submit changes from your fork to the original repo.

Reference: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by billtlee** [comment]
Sure, I can do it in the next few days.

**Comment by billtlee** [comment]
created a pull request

**Comment by fmsouza** [comment]
Fixed by https://github.com/fmsouza/ethereum-wallet/pull/10.
